### ISSUE TITLE
Arabic labeled data

### ISSUE THREAD

**Issue by Fatima-200159617** [mohaddad/COVID-FAKES#1]
Greetings,
Thanks for the dataset. I am interested in the Arabic data but I can only find the English one. Could you please advice.

**Comment by Fatima-200159617** [comment]
I aprreciate if you can share a copy of the paper.

**Comment by mohaddad** [comment]
Hi Fatima,
The Arabic data is now available!!
Wishing you all the best!!.... Mohamed

**Comment by mohaddad** [comment]
(https://github.com/mohaddad/COVID-FAKES/tree/COVID-FAKES-A)

**Comment by mohaddad** [comment]
[Paper's Link](https://doi.org/10.1007/978-3-030-57796-4_25)

**Comment by Fatima-200159617** [comment]
Thanks a lot for sharing.

**Comment by mohaddad** [comment]
You are very welcome!!

Good luck with your research!!
